### ISSUE TITLE
    - troopers/mangopay-bundle 2.0.3 requires troopers/ajax-bundle ~1.2.2 -> no matching package found.

### ISSUE THREAD

**Issue by allan-simon** [Troopers/MangopayBundle#28]
sorry to spam you with issue ^^'

**Comment by lenybernard** [comment]
NP, thank you and sorry for this !
Does this [commit](https://github.com/Troopers/MangopayBundle/commit/8f2d812e0318ee73d8dbc8cd50a7b2cfe710d945) fix your issue ?

**Comment by allan-simon** [comment]
hmm I think packagist has some kind of cache, because it still reference the version with dependencies on 1.2.2

**Comment by allan-simon** [comment]
seems ok now, certainly the time for the cache to be refreshed
