### ISSUE TITLE
Documentation : Installation et configuration

### ISSUE THREAD

**Issue by flavienaudin** [Troopers/MangopayBundle#48]
Bonjour,
Votre plugin semble intéressant pour faciliter l'utilisation de MangoPay au sein d'un projet Symfony. Est-ce que sa maintenance est assurée sur le long terme ?
La documentation n'est pas très détaillée notamment concernant la configuration et les classes à implémenter (s'il y en a). Est-ce qu'il y a une autre source d'information ou des cas d'utilisation/démo ?
Merci pour votre retour.
Flavien

**Comment by paulandrieux** [comment]
Hi Flavien,
This bundle is supported by the Troopers agency and the community, we cannot guarantee any long term support but we will handle every (welcomed) pull request.
All the documentation is in the README, the configuration is pretty concise, you just have to define your client id, password and the api base url.
About the classes, this bundle is mailly about the Helpers that ease usage of the official Mangopay SDK. You have some entities to store MP related data and a controller that handle payment with custom payment form.
We sadly do not have any public repo where this bundle is used.

**Comment by flavienaudin** [comment]
Hi Paul,
About README, I understood clearly the first two parameters : client id and password, but the api base url was first not obvious, but looking into your code, I find it corresponds to the production or sandbox url, right ?
Generally, I guess that continuing to read the mangopay API documentation will help me to understand the workflow and so the interest of this bundle.
Thank you for the answer.
